- README.md
> Fixed minor typo in README.md

- contracts/StatusContribution.sol
- test/contribution.js
Reverts status-im/status-network-token#11
> Revert "Limit gasPrice in buy"

- contracts/StatusContribution.sol
- test/contribution.js
This should prevent a lot of throw transactions.  And should be more people that is able to participate.
> asymptotic ceil

- .travis.yml
- README.md
- contracts/MultisigWallet.sol
- package.json
Cache packages for faster testing.
> Fix Travis CI and tests failing

- contracts/StatusContribution.sol
- test/claimExternal.js
- test/contribution.js
This PR limits the quantity of ETH that each SGT can spend in the preferenceSGT contribution period.
> SGT fixed limit and contribution period. Set also sgtPreferenceBlock as variable.

- contracts/DevTokensHolder.sol
- contracts/DynamicCeiling.sol
- contracts/MiniMeToken.sol
- contracts/MultisigWallet.sol
- contracts/SGT.sol
- contracts/SGTExchanger.sol
- contracts/SNTPlaceHolder.sol
- contracts/StatusContribution.sol
Hi! :)
I just started reviewing your contracts (out of personal interest) and while doing so corrected a few spelling errors and did some minor clarifications in comments. 
This commit contains only changes in comments (and one single removed whitespace after an opening parenthesis).
> Changes in comments

- contracts/ContributionWallet.sol
- contracts/DevTokensHolder.sol
- contracts/DynamicCeiling.sol
- contracts/Owned.sol
- contracts/SGT.sol
- contracts/SGTExchanger.sol
- contracts/SNTPlaceHolder.sol
- contracts/StatusContribution.sol
- test/helpers/SNTPlaceHolderMock.sol
- test/helpers/StatusContributionMock.sol
> contracts: Explicit function modifiers

- contracts/StatusContribution.sol
> contracts: StatusContribution: Fix `CurvePoint` extracted members

- contracts/DevTokensHolder.sol
- contracts/DynamicCeiling.sol
- contracts/SGTExchanger.sol
- contracts/SNTPlaceHolder.sol
- contracts/SafeMath.sol
- contracts/StatusContribution.sol
> contracts: Use Safemath from OpenZeppelin

- contracts/ContributionWallet.sol
- contracts/StatusContribution.sol
- test/claimExternal.js
- test/contribution.js
> contracts: Refactor `stopBlock` to `endBlock`

- contracts/ContributionWallet.sol
- contracts/DevTokensHolder.sol
- contracts/DynamicCeiling.sol
- contracts/SGT.sol
- contracts/SGTExchanger.sol
- contracts/SNTPlaceHolder.sol
- contracts/StatusContribution.sol
> Explicit sizes

- .flake8
- .gitignore
- .pylintrc
- contracts/DynamicCeiling.sol
- contracts/StatusContribution.sol
- mypy.ini
- scripts/ceiling_curve_calc.py
- test/claimExternal.js
- test/contribution.js
- test/dynamicCeiling.js
- test/helpers/DevTokensHolderMock.sol
- test/helpers/SNTPlaceHolderMock.sol
- test/helpers/StatusContributionMock.sol
- test/helpers/hiddenCurves.js
- test/helpers/hiddenPoints.js
> Moving curves

- contracts/StatusContribution.sol
- test/claimExternal.js
- test/contribution.js
> StatusContribution: Remove SGT contribution period

- contracts/DynamicCeiling.sol
- contracts/StatusContribution.sol
- test/claimExternal.js
- test/contribution.js
- test/dynamicCeiling.js
- test/helpers/hiddenCurves.js
> DynamicCeiling: Implement `slopeFactor` and `collectMinimum` per curve

- contracts/DynamicCeiling.sol
- test/dynamicCeiling.js
> DynamicCeiling: Implement reveal of multiple curves at once

- test/contribution.js
- test/helpers/assertFail.js
This PR replaces #70 with the test that failed fixed.
> Blockchain labs nz tests/fail assertion

- contracts/StatusContribution.sol
- test/dynamicCeiling.js
Extra logic not worth it.
Reverts status-im/status-network-token#80
> Revert "First Ceiling SGT Holders up to limit"

- contracts/StatusContribution.sol
> Enforce fail-safe for total collected

- contracts/StatusContribution.sol
> contracts: Minor comment fixes

- contracts/SGTExchanger.sol
> contracts: SGTExchanger: Fix space formatting

- contracts/StatusContribution.sol
> contracts: StatusContribution: Fix `setGuaranteedAddress` comment

- contracts/StatusContribution.sol
> contracts: StatusContribution: Fix formatting for antispam

- migrations/2_deploy_contracts.js
- truffle.js
> migrations: Parallelization
